export const countries = [
  { code: "KOR", name: "Republic of Korea" },
  { code: "USA", name: "United States" },
  { code: "JPN", name: "Japan" },
  { code: "CHN", name: "China" },
  { code: "CAN", name: "Canada" },
  { code: "FRA", name: "France" },
  { code: "GBR", name: "United Kingdom" },
  { code: "AUS", name: "Australia" },
  { code: "DEU", name: "Germany" },
  { code: "ITA", name: "Italy" },
  { code: "ESP", name: "Spain" },
  { code: "MEX", name: "Mexico" },
  { code: "RUS", name: "Russia" },
  { code: "IND", name: "India" },
  { code: "BRA", name: "Brazil" },
  { code: "SGP", name: "Singapore" },
  { code: "THA", name: "Thailand" },
  { code: "VNM", name: "Vietnam" },
  { code: "PHL", name: "Philippines" },
  { code: "IDN", name: "Indonesia" },
  { code: "NLD", name: "Netherlands" },
  { code: "BEL", name: "Belgium" },
  { code: "CHE", name: "Switzerland" },
  { code: "SWE", name: "Sweden" },
  { code: "NOR", name: "Norway" },
  { code: "DNK", name: "Denmark" },
  { code: "FIN", name: "Finland" },
  { code: "POL", name: "Poland" },
  { code: "AUT", name: "Austria" },
  { code: "CZE", name: "Czech Republic" },
  { code: "HUN", name: "Hungary" },
  { code: "PRT", name: "Portugal" },
  { code: "GRC", name: "Greece" },
  { code: "TUR", name: "Turkey" },
  { code: "SAU", name: "Saudi Arabia" },
  { code: "ARE", name: "United Arab Emirates" },
  { code: "QAT", name: "Qatar" },
  { code: "KWT", name: "Kuwait" },
  { code: "ZAF", name: "South Africa" },
  { code: "EGY", name: "Egypt" },
  { code: "ISR", name: "Israel" },
  { code: "ARG", name: "Argentina" },
  { code: "CHL", name: "Chile" },
  { code: "COL", name: "Colombia" },
  { code: "PER", name: "Peru" },
  { code: "NZL", name: "New Zealand" },
  { code: "IRL", name: "Ireland" },
  { code: "LUX", name: "Luxembourg" },
  { code: "ISL", name: "Iceland" }
];
